fragment ArtParts on Art {
  __typename
  artProjects {
    __typename
    id
    title
    category
    year
    description
    body
    link
    linkText
    previewImage
    images
  }
}

fragment WorkParts on Work {
  __typename
  workProjects {
    __typename
    id
    title
    category
    year
    description
    images {
      __typename
      src
      alt
    }
    imageLayout
  }
}

fragment AboutParts on About {
  __typename
  title
  image
  intro
  bio
  contact
  arenaBox {
    __typename
    title
    description
    link
  }
  philosophy
  footer
}
